#!/usr/bin/env python3
"""Cross-model judge for an executed delayed-value replay case."""

from __future__ import annotations

import argparse
import json
import os
import re
import time
from datetime import datetime, timezone
from pathlib import Path
from typing import Any
from urllib import request
from urllib.error import HTTPError, URLError


ROOT = Path(__file__).resolve().parents[1]
DOC_DIR = ROOT / "docs" / "co_pilot_ai_scientist_v3"
DEFAULT_CASE_RUN = DOC_DIR / "experiments" / "delayed_value_replay_case_paper_105_review_1_20260602_235500"
CONDITIONS = [
    "paper_only",
    "raw_review_guided",
    "six_gate_hybrid_guided",
    "shuffled_review_control",
]


def _utc_now() -> str:
    return datetime.now(timezone.utc).replace(microsecond=0).isoformat().replace("+00:00", "Z")


def _rel(path: Path) -> str:
    return str(path.relative_to(ROOT))


def _load_json(path: Path) -> Any:
    return json.loads(path.read_text(encoding="utf-8"))


def _write(path: Path, text: str) -> str:
    path.write_text(text.rstrip() + "\n", encoding="utf-8")
    return _rel(path)


def _call_monica(
    *,
    model: str,
    messages: list[dict[str, str]],
    max_tokens: int,
    temperature: float,
) -> dict[str, Any]:
    api_key = os.environ["MONICA_API_KEY"]
    base_url = os.environ.get("MONICA_BASE_URL", "https://openapi.monica.im/v1").rstrip("/")
    body = json.dumps(
        {
            "model": model,
            "messages": messages,
            "max_tokens": max_tokens,
            "temperature": temperature,
        }
    ).encode("utf-8")
    req = request.Request(
        f"{base_url}/chat/completions",
        data=body,
        headers={
            "Authorization": f"Bearer {api_key}",
            "Content-Type": "application/json",
        },
        method="POST",
    )
    started = time.time()
    last_error = None
    for attempt in range(3):
        try:
            with request.urlopen(req, timeout=180) as resp:  # noqa: S310 - fixed HTTPS API endpoint.
                payload = json.loads(resp.read().decode("utf-8"))
            payload["_latency_seconds"] = round(time.time() - started, 3)
            payload["_attempts"] = attempt + 1
            return payload
        except (HTTPError, URLError) as exc:
            last_error = repr(exc)
            time.sleep(2.0 * (attempt + 1))
    raise RuntimeError(f"Monica request failed after retries: {last_error}")


def _message_text(response: dict[str, Any]) -> str:
    return response["choices"][0]["message"]["content"]


def _extract_json_object(text: str) -> dict[str, Any]:
    stripped = text.strip()
    fenced = re.search(r"```(?:json)?\s*(\{.*?\})\s*```", stripped, flags=re.S)
    if fenced:
        return json.loads(fenced.group(1))
    start = stripped.find("{")
    end = stripped.rfind("}")
    if start == -1 or end == -1 or end <= start:
        raise ValueError("model response does not contain a JSON object")
    return json.loads(stripped[start : end + 1])


def _judge_prompt(summary: dict[str, Any], spec: dict[str, Any]) -> str:
    generated = summary["generated"]
    return f"""
You are an independent conservative judge for a Temporal Frontier Replay case.

The four artifacts below were already generated by another model. Your task is
to score them; do not rewrite them and do not infer completed experiments.

Case title: {summary['title']}
Case ID: {summary['case_id']}
Source spec: {summary['source_spec']}

Preregistered positive delayed-value rule:
{json.dumps(spec['positive_delayed_value_rule'], ensure_ascii=False, indent=2)}

Short-term metrics:
{json.dumps(spec['short_term_metrics'], ensure_ascii=False, indent=2)}

Frontier metrics:
{json.dumps(spec['frontier_metrics'], ensure_ascii=False, indent=2)}

Generated artifacts:
{json.dumps(generated, ensure_ascii=False, indent=2)}

Return strict JSON only:
{{
  "per_condition": {{
    "paper_only": {{
      "short_term_score": 1-5,
      "frontier_alignment_score": 1-5,
      "actionability_score": 1-5,
      "specificity_score": 1-5,
      "claim_calibration_score": 1-5,
      "overall": 1-5,
      "rationale": "..."
    }},
    "raw_review_guided": {{ "... same fields ...": "" }},
    "six_gate_hybrid_guided": {{ "... same fields ...": "" }},
    "shuffled_review_control": {{ "... same fields ...": "" }}
  }},
  "winner_short_term": "paper_only|raw_review_guided|six_gate_hybrid_guided|shuffled_review_control|tie",
  "winner_frontier": "paper_only|raw_review_guided|six_gate_hybrid_guided|shuffled_review_control|tie",
  "model_delayed_value_label": "positive|negative|mixed_or_inconclusive",
  "delayed_value_rationale": "...",
  "failure_modes_observed": ["..."],
  "claim_boundary": "..."
}}
""".strip()


def _normalize_scores(scoring: dict[str, Any]) -> dict[str, Any]:
    per = scoring.get("per_condition", {})
    normalized: dict[str, Any] = {}
    for condition in CONDITIONS:
        row = per.get(condition) or {}
        out = {}
        for key in [
            "short_term_score",
            "frontier_alignment_score",
            "actionability_score",
            "specificity_score",
            "claim_calibration_score",
            "overall",
        ]:
            value = row.get(key)
            if not isinstance(value, (int, float)):
                value = 0
            out[key] = float(value)
        out["rationale"] = row.get("rationale", "")
        normalized[condition] = out
    scoring["per_condition"] = normalized

    def _best(metric: str) -> str:
        values = {condition: normalized[condition][metric] for condition in CONDITIONS}
        best_value = max(values.values())
        winners = [condition for condition, value in values.items() if value == best_value]
        return winners[0] if len(winners) == 1 else "tie"

    scoring["winner_short_term"] = _best("short_term_score")
    scoring["winner_frontier"] = _best("frontier_alignment_score")
    model_label = scoring.get("model_delayed_value_label")
    if model_label is None:
        model_label = scoring.get("delayed_value_label")
    scoring["model_delayed_value_label"] = model_label
    paper = normalized["paper_only"]
    shuffled = normalized["shuffled_review_control"]
    positives = []
    for condition in ["raw_review_guided", "six_gate_hybrid_guided"]:
        row = normalized[condition]
        if (
            row["short_term_score"] < paper["short_term_score"]
            and row["frontier_alignment_score"] > paper["frontier_alignment_score"]
            and row["frontier_alignment_score"] > shuffled["frontier_alignment_score"]
            and row["actionability_score"] >= 4
            and row["specificity_score"] >= 4
        ):
            positives.append(condition)
    if positives:
        scoring["strict_delayed_value_label"] = "positive"
        scoring["strict_best_review_signal"] = positives[0]
        scoring["strict_label_note"] = "strict preregistered delayed-value rule satisfied"
    else:
        scoring["strict_delayed_value_label"] = "mixed_or_inconclusive"
        scoring["strict_best_review_signal"] = "none"
        scoring["strict_label_note"] = (
            "strict preregistered delayed-value rule not satisfied under this judge"
        )
    return scoring


def _aggregate(judgements: dict[str, dict[str, Any]]) -> dict[str, Any]:
    strict_counts: dict[str, int] = {}
    model_counts: dict[str, int] = {}
    frontier_winners: dict[str, int] = {}
    short_winners: dict[str, int] = {}
    for judgement in judgements.values():
        strict = judgement.get("strict_delayed_value_label", "missing")
        model = judgement.get("model_delayed_value_label", "missing")
        strict_counts[strict] = strict_counts.get(strict, 0) + 1
        model_counts[model] = model_counts.get(model, 0) + 1
        fw = judgement.get("winner_frontier", "missing")
        sw = judgement.get("winner_short_term", "missing")
        frontier_winners[fw] = frontier_winners.get(fw, 0) + 1
        short_winners[sw] = short_winners.get(sw, 0) + 1
    return {
        "judge_count": len(judgements),
        "strict_label_counts": strict_counts,
        "model_label_counts": model_counts,
        "frontier_winner_counts": frontier_winners,
        "short_term_winner_counts": short_winners,
        "all_strict_positive": strict_counts.get("positive", 0) == len(judgements) and bool(judgements),
        "any_model_strict_disagreement": any(
            item.get("model_delayed_value_label") != item.get("strict_delayed_value_label")
            for item in judgements.values()
        ),
    }


def _markdown(summary: dict[str, Any]) -> str:
    lines = [
        "# Delayed-Value Replay Cross-Model Judge",
        "",
        f"- Run ID: `{summary['run_id']}`",
        f"- Timestamp UTC: `{summary['timestamp_utc']}`",
        f"- Source case run: `{summary['source_case_run']}`",
        f"- Models attempted: `{', '.join(summary['models_attempted'])}`",
        f"- Models succeeded: `{', '.join(summary['models_succeeded'])}`",
        f"- Strict label counts: `{summary['aggregate']['strict_label_counts']}`",
        f"- Model label counts: `{summary['aggregate']['model_label_counts']}`",
        f"- Frontier winner counts: `{summary['aggregate']['frontier_winner_counts']}`",
        f"- Any model/strict disagreement: `{summary['aggregate']['any_model_strict_disagreement']}`",
        "",
        "## Per-Model Results",
        "",
    ]
    for model, judgement in summary["judgements"].items():
        lines.append(
            f"- `{model}`: model label `{judgement.get('model_delayed_value_label')}`, "
            f"strict label `{judgement.get('strict_delayed_value_label')}`, "
            f"short-term winner `{judgement.get('winner_short_term')}`, "
            f"frontier winner `{judgement.get('winner_frontier')}`"
        )
    if summary.get("errors"):
        lines.extend(["", "## Errors", ""])
        for model, error in summary["errors"].items():
            lines.append(f"- `{model}`: {error}")
    lines.extend(["", "## Claim Boundary", "", summary["claim_boundary"], ""])
    return "\n".join(lines)


def _update_manifest(paths: list[str], summary: dict[str, Any]) -> None:
    manifest_path = DOC_DIR / "repro_manifest.json"
    manifest = _load_json(manifest_path)
    artifacts = manifest.setdefault("current_artifacts", [])
    for path in paths:
        if path not in artifacts:
            artifacts.append(path)
    manifest["delayed_value_replay_cross_model_judge"] = {
        "run_id": summary["run_id"],
        "summary": summary["summary_path"],
        "source_case_run": summary["source_case_run"],
        "models_succeeded": summary["models_succeeded"],
        "strict_label_counts": summary["aggregate"]["strict_label_counts"],
        "model_label_counts": summary["aggregate"]["model_label_counts"],
        "claim_boundary": summary["claim_boundary"],
    }
    manifest_path.write_text(json.dumps(manifest, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--case-run", default=str(DEFAULT_CASE_RUN))
    parser.add_argument("--models", nargs="+", default=["claude-3-7-sonnet-latest", "gemini-2.5-flash"])
    parser.add_argument("--run-id", default=None)
    parser.add_argument("--max-tokens", type=int, default=6000)
    parser.add_argument("--no-manifest", action="store_true")
    args = parser.parse_args()

    if not os.environ.get("MONICA_API_KEY"):
        raise SystemExit("MONICA_API_KEY is required. Source ~/.codex/env before running.")

    case_run = Path(args.case_run)
    if not case_run.is_absolute():
        case_run = ROOT / case_run
    case_summary = _load_json(case_run / "summary.json")
    spec = _load_json(ROOT / case_summary["source_spec"])
    run_id = args.run_id or f"delayed_value_replay_cross_model_judge_{datetime.now(timezone.utc).strftime('%Y%m%d_%H%M%S')}"
    out_dir = DOC_DIR / "experiments" / run_id
    out_dir.mkdir(parents=True, exist_ok=True)
    prompt = _judge_prompt(case_summary, spec)

    judgements: dict[str, dict[str, Any]] = {}
    errors: dict[str, str] = {}
    paths = [_write(out_dir / "judge_prompt.txt", prompt)]
    for model in args.models:
        try:
            response = _call_monica(
                model=model,
                messages=[
                    {"role": "system", "content": "Return strict JSON. Score conservatively."},
                    {"role": "user", "content": prompt},
                ],
                max_tokens=args.max_tokens,
                temperature=0.05,
            )
            text = _message_text(response)
            judgement = _normalize_scores(_extract_json_object(text))
            judgement["_latency_seconds"] = response.get("_latency_seconds")
            judgement["_attempts"] = response.get("_attempts")
            judgements[model] = judgement
            paths.append(_write(out_dir / f"{model}_raw_response.txt", text))
            paths.append(_write(out_dir / f"{model}_judgement.json", json.dumps(judgement, ensure_ascii=False, indent=2)))
        except Exception as exc:  # noqa: BLE001 - archived as model availability evidence.
            errors[model] = repr(exc)

    summary: dict[str, Any] = {
        "run_id": run_id,
        "timestamp_utc": _utc_now(),
        "status": "delayed_value_replay_cross_model_judge",
        "source_case_run": _rel(case_run),
        "models_attempted": args.models,
        "models_succeeded": sorted(judgements),
        "judgements": judgements,
        "errors": errors,
        "aggregate": _aggregate(judgements),
        "claim_boundary": (
            "This cross-model judge scores already generated four-condition mini-paper "
            "artifacts. It reduces same-model scoring bias but is still model evaluation, "
            "not human expert review or benchmark execution."
        ),
    }
    summary_path = out_dir / "summary.json"
    summary["summary_path"] = _rel(summary_path)
    paths.append(_write(summary_path, json.dumps(summary, ensure_ascii=False, indent=2)))
    paths.append(_write(out_dir / "README.md", _markdown(summary)))
    summary["artifacts_written"] = paths
    _write(summary_path, json.dumps(summary, ensure_ascii=False, indent=2))
    if not args.no_manifest:
        _update_manifest(paths + ["scripts/run_delayed_value_replay_cross_model_judge.py"], summary)
    print(json.dumps(summary, ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()
